services:
    phpbbservices.smartfeed.controller.ui:
        class: phpbbservices\smartfeed\controller\ui
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
            - @dbal.conn
            - @auth
            - %core.root_path%
    phpbbservices.smartfeed.controller.feed:
        class: phpbbservices\smartfeed\controller\feed
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
            - @dbal.conn
            - @auth
            - %core.root_path%
            - @request
    phpbbservices.smartfeed.listener:
        class: phpbbservices\smartfeed\event\main_listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - %core.php_ext%
        tags:
            - { name: event.listener }